import 'package:keuanganku/backend/database/helper/income.dart';
import 'package:keuanganku/backend/database/helper/wallet.dart';
import 'package:keuanganku/backend/database/model/model.dart';

/// The [DBModelIncome] class represents an income entry to be stored in the
/// application's database. This class extends the [DBModel] class.
class DBModelIncome extends DBModel {
  /// The unique ID of the income (optional).
  int? id;

  /// The title or short description of the income.
  String? title;

  /// The amount of money received.
  double? amount;

  /// Additional description of the income.
  String? description;

  /// The ID of the wallet associated with this income.
  int? wallet_id;

  /// The ID of the income category (optional).
  int? category_id;

  /// The date and time of the income in string format.
  String? datetime;

  /// Creates a new instance of [DBModelIncome].
  ///
  /// Parameters:
  /// - [id]: The unique ID of the income.
  /// - [title]: The title or short description of the income.
  /// - [amount]: The amount of money received.
  /// - [description]: Additional description of the income.
  /// - [wallet_id]: The ID of the wallet associated with this income.
  /// - [category_id]: The ID of the income category.
  /// - [datetime]: The date and time of the income in string format.
  DBModelIncome({
    this.id,
    this.title,
    this.amount,
    this.description,
    this.wallet_id,
    this.category_id,
    this.datetime
  });

  /// Converts the [DBModelIncome] instance into a [Map<String, dynamic>] format
  /// for storing in the database.
  ///
  /// Returns:
  /// - A map representing the income data.
  @override
  Map<String, dynamic> toJson(){
    return {
      'id': id,
      'title': title,
      'amount': amount,
      'description': description,
      'wallet_id': wallet_id,
      'category_id': category_id,
      'datetime': datetime,
    };
  }

  /// Creates a [DBModelIncome] instance from a JSON object.
  ///
  /// Parameters:
  /// - [json]: A [Map<String, dynamic>] containing the income data.
  ///
  /// Returns:
  /// - A [DBModelIncome] instance with the populated data.
  @override
  DBModelIncome fromJson(Map<String, dynamic> json) {
    return DBModelIncome(
      id: json['id'],
      title: json['title'],
      amount: json['amount'],
      wallet_id: json['wallet_id'],
      category_id: json['category_id'],
      datetime: json['datetime'],
    );
  }

  /// Inserts the income into the database.
  ///
  /// This function will insert the income into the database and set the `id` property
  /// with the new ID generated by the database.
  ///
  /// Returns:
  /// - A [Future<void>] indicating the completion of the operation.
  Future<void> insert() async {
    int id = await DBHelperIncome().insert(data: this);
    this.id = id;  // Use `this.id` to set the instance variable
  }

  /// Inserts the income into the database and updates the wallet's total income.
  ///
  /// This function will insert the income and update the `wallet.total_income`.
  ///
  /// Returns:
  /// - A [Future<void>] indicating the completion of the operation.
  Future<void> insertAndUpdateWalletIncome() async {
    await insert();
    await DBHelperWallet().addIncome(walletId: wallet_id!, income: amount!);
  }
}
